# Configuration for hyprlock which handles the lockscreen

general {
	grace = 0
}

auth {
  fingerprint {
    enabled = true
  }
}

background {
	monitor = 
	path = /home/biskyy/.config/wallpapers/1.jpg

	blur_passes = 1
#	blur_size = 10
#	noise = 0.1
#	contrast = 0.7
#	brightness = 0.7
#	vibrancy = 0.1
#	vibrancy_darkness = 0.0
}

input-field {
	monitor = eDP-1

  inner_color = rgba(255, 255, 255, 0.5)

	size = 250, 40
	dots_size = 0.1
	dots_center = true

	fade_on_empty = false	

	placeholder_text = <i>password</i>

	hide_input = false
	
	position = 0, -200
	halign = center
	valign = center
}

# Show time
label {
	monitor = eDP-1

	text = cmd[update:1000] date +"%-I:%M %p"
	text_align = center

	color = rgba(255, 255, 255, 0.9)

	font_size = 150
	font_family = SF Pro Text Heavy

	position = 0, 200
    halign = center
    valign = center
}

#label {
#	monitor = HDMI-A-1

#	text = Welcome back, $USER
#	text_align = center

#	color = rgba(255, 255, 255, 0.9)

#	font_size = 20
#	font_family = SF Pro Text Semibold

#	position = 0, -150
#	halign = center
#	valign = center

#}
