# https://wiki.hyprland.org/Configuring/Variables/#input
input {
  kb_layout = us,ro
  kb_variant = mac,std
  kb_model =
  kb_options = grp:alt_space_toggle
  kb_rules =

  follow_mouse = 1

  sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

  # accel_profile = adaptive

  touchpad {
    natural_scroll = true
    disable_while_typing = false
    scroll_factor = 0.5
  }
}

# https://wiki.hyprland.org/Configuring/Variables/#gestures
gestures {
  workspace_swipe = false
}

# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
# Example per-device config
# device {
#     name = epic-mouse-v1
#     sensitivity = -0.5
# }

cursor {
  default_monitor = eDP-1
}
