# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

workspace = 1, persistent:true
workspace = 2, persistent:true
workspace = 3, persistent:true
workspace = 4, persistent:true

# Example windowrule v1
# windowrule = float, ^(kitty)$

# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

windowrulev2 = immediate, class:^(hyprlock)$
windowrulev2 = stayfocused, class:^(hyprlock)$
windowrulev2 = fullscreen, title:^(Rain World)$

# windowrulev2 = float, title:^(Unity)$
# windowrulev2 = center, title:^(Unity)$
# windowrulev2 = float, title:^(Extract — Dolphin)

# zen
windowrulev2 = float, title:^(About Zen Browser)
# windowrulev2 = suppressevent activate activatefocus, initialTitle:^(Zen Browser)$ these two dont work
# windowrulev2 = noinitialfocus, initialTitle:^(Zen Browser)$
windowrulev2 = workspace 2, initialTitle:^(Zen Browser)$
windowrulev2 = float, class:^(zen), title:^(Library)
windowrulev2 = float, title:^(File Operation Progress)$

# zen pip
windowrulev2 = float, class:^(zen), title:^(Picture-in-Picture)
windowrulev2 = float, class:^(zen), title:^(Conectează-te – Conturi Google — Zen Browser)
windowrulev2 = move 888 493, class:^(zen), title:^(Picture-in-Picture)
windowrulev2 = size 374 210, class:^(zen), title:^(Picture-in-Picture)

# clipboard
windowrulev2 = float, class:(clipse)
windowrulev2 = size 450 400, class:(clipse)
windowrulev2 = move 5% 40%, class:(clipse)
windowrulev2 = stayfocused, class:(clipse)

# xdg-portal
windowrulev2 = float, title:^(Open File)$
windowrulev2 = size 800 600, title:^(Open File)$

windowrulev2 = float, class:^(hyprland-share-picker)$
windowrulev2 = size 800 600, class:^(hyprland-share-picker)$

# ark
windowrulev2 = float, class:^(org.kde.ark)

# whatsapp
windowrulev2 = float, class:^(wasistlos)
windowrulev2 = size 1000 600, class:^(wasistlos)
# windowrulev2 = nofocus,class:^(ags)$,title:^(ags_overlay_\d+)$
# windowrulev2 = noinitialfocus,class:^(ags)$,title:^(ags_overlay_\d+)$
