modmap:
  - name: CapsLock to Esc/Ctrl
    remap:
      CapsLock:
        held: Super_R
        alone: Esc
keymap:
  - name: Ctrl+IJKL to Arrow Keys
    remap:
      Super-k: Up
      Super-j: Down
      Super-h: Left
      Super-l: Right
