virtual_modifiers:
  - CapsLock
modmap:
  - remap:
      CapsLock:
        held: CapsLock
        alone: Esc
keymap:
  - name: Global
    remap:
      CapsLock-h: Left
      CapsLock-j: Down
      CapsLock-k: Up
      CapsLock-l: Right
